services:
  app:
    image: url-project:local
    environment:
      CONFIG_PATH: "/config.yaml"
    container_name: ps-backend
    depends_on:
      - mongodb_container
    networks:
      - ps

  mongodb_container:
      image: mongo:latest
      container_name: ps-mongodb
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: myuser
        MONGO_INITDB_ROOT_PASSWORD: mypass
        MONGODB_URL: mongodb://myuser:mypass@localhost:27017
      volumes:
        - mongodbdatacontainer:/data/db
      networks:
        - ps
      command: mongod
volumes:
  mongodbdatacontainer:

networks:
  ps: