env: "prod" # local dev prod   РЕЖИМ РАБОТЫ
http_server:
  address: "localhost:8082" ------------------АДРЕСС ( ХОСТ:ПОРТ) для хттп сервера (8080)
  timeout: 4s
  idle_timeout: 60s
  userApp: -----------------------------------Ваш юзер приложения
  passwordApp: -------------------------------Пароль от Сервера Приложения

db_server:
  dbhost: localhost---------------------------ХОСТ ДБ
  dbport: "27017"   --------------------------ПОРТ ОТ ДБ
  aliasLength: -------------------------------6 Произвольная длина
  userDB: ------------------------------------Ваш Юзер от БД
  passwordDB: --------------------------------Ваш пароль от БД